package ru.tanexc.siderakt.presentation.ui.theme.Colors

import androidx.compose.ui.graphics.Color

data class GreenColorScheme(
    override val md_theme_light_primary: Color = Color(0xFF006D36),
    override val md_theme_light_onPrimary: Color = Color(0xFFFFFFFF),
    override val md_theme_light_primaryContainer: Color = Color(0xFF69FE9A),
    override val md_theme_light_onPrimaryContainer: Color = Color(0xFF00210C),
    override val md_theme_light_secondary: Color = Color(0xFF506352),
    override val md_theme_light_onSecondary: Color = Color(0xFFFFFFFF),
    override val md_theme_light_secondaryContainer: Color = Color(0xFFD3E8D3),
    override val md_theme_light_onSecondaryContainer: Color = Color(0xFF0E1F12),
    override val md_theme_light_tertiary: Color = Color(0xFF3A656E),
    override val md_theme_light_onTertiary: Color = Color(0xFFFFFFFF),
    override val md_theme_light_tertiaryContainer: Color = Color(0xFFBDEAF5),
    override val md_theme_light_onTertiaryContainer: Color = Color(0xFF001F25),
    override val md_theme_light_error: Color = Color(0xFFBA1A1A),
    override val md_theme_light_errorContainer: Color = Color(0xFFFFDAD6),
    override val md_theme_light_onError: Color = Color(0xFFFFFFFF),
    override val md_theme_light_onErrorContainer: Color = Color(0xFF410002),
    override val md_theme_light_background: Color = Color(0xFFFCFDF7),
    override val md_theme_light_onBackground: Color = Color(0xFF191C19),
    override val md_theme_light_surface: Color = Color(0xFFFCFDF7),
    override val md_theme_light_onSurface: Color = Color(0xFF191C19),
    override val md_theme_light_surfaceVariant: Color = Color(0xFFDDE5DA),
    override val md_theme_light_onSurfaceVariant: Color = Color(0xFF414941),
    override val md_theme_light_outline: Color = Color(0xFF717970),
    override val md_theme_light_inverseOnSurface: Color = Color(0xFFF0F1EC),
    override val md_theme_light_inverseSurface: Color = Color(0xFF2E312E),
    override val md_theme_light_inversePrimary: Color = Color(0xFF48E181),
    override val md_theme_light_shadow: Color = Color(0xFF000000),
    override val md_theme_light_surfaceTint: Color = Color(0xFF006D36),
    override val md_theme_light_outlineVariant: Color = Color(0xFFC1C9BF),
    override val md_theme_light_scrim: Color = Color(0xFF000000),

    override val md_theme_dark_primary: Color = Color(0xFF48E181),
    override val md_theme_dark_onPrimary: Color = Color(0xFF003919),
    override val md_theme_dark_primaryContainer: Color = Color(0xFF005227),
    override val md_theme_dark_onPrimaryContainer: Color = Color(0xFF69FE9A),
    override val md_theme_dark_secondary: Color = Color(0xFFB7CCB7),
    override val md_theme_dark_onSecondary: Color = Color(0xFF233426),
    override val md_theme_dark_secondaryContainer: Color = Color(0xFF394B3B),
    override val md_theme_dark_onSecondaryContainer: Color = Color(0xFFD3E8D3),
    override val md_theme_dark_tertiary: Color = Color(0xFFA2CED8),
    override val md_theme_dark_onTertiary: Color = Color(0xFF01363F),
    override val md_theme_dark_tertiaryContainer: Color = Color(0xFF204D56),
    override val md_theme_dark_onTertiaryContainer: Color = Color(0xFFBDEAF5),
    override val md_theme_dark_error: Color = Color(0xFFFFB4AB),
    override val md_theme_dark_errorContainer: Color = Color(0xFF93000A),
    override val md_theme_dark_onError: Color = Color(0xFF690005),
    override val md_theme_dark_onErrorContainer: Color = Color(0xFFFFDAD6),
    override val md_theme_dark_background: Color = Color(0xFF191C19),
    override val md_theme_dark_onBackground: Color = Color(0xFFE2E3DE),
    override val md_theme_dark_surface: Color = Color(0xFF191C19),
    override val md_theme_dark_onSurface: Color = Color(0xFFE2E3DE),
    override val md_theme_dark_surfaceVariant: Color = Color(0xFF414941),
    override val md_theme_dark_onSurfaceVariant: Color = Color(0xFFC1C9BF),
    override val md_theme_dark_outline: Color = Color(0xFF8B938A),
    override val md_theme_dark_inverseOnSurface: Color = Color(0xFF191C19),
    override val md_theme_dark_inverseSurface: Color = Color(0xFFE2E3DE),
    override val md_theme_dark_inversePrimary: Color = Color(0xFF006D36),
    override val md_theme_dark_shadow: Color = Color(0xFF000000),
    override val md_theme_dark_surfaceTint: Color = Color(0xFF48E181),
    override val md_theme_dark_outlineVariant: Color = Color(0xFF414941),
    override val md_theme_dark_scrim: Color = Color(0xFF000000),


    override val seed: Color = Color(0xFF00BC61)
) : AppColorScheme