package ru.tanexc.siderakt.presentation.ui.theme.Colors

import androidx.compose.ui.graphics.Color
import ru.tanexc.siderakt.presentation.ui.theme.Colors.AppColorScheme

data class OrangeColorScheme(

    override val md_theme_light_primary: Color = Color(0xFF97480B),
    override val md_theme_light_onPrimary: Color = Color(0xFFFFFFFF),
    override val md_theme_light_primaryContainer: Color = Color(0xFFFFDBC8),
    override val md_theme_light_onPrimaryContainer: Color = Color(0xFF321200),
    override val md_theme_light_secondary: Color = Color(0xFF765847),
    override val md_theme_light_onSecondary: Color = Color(0xFFFFFFFF),
    override val md_theme_light_secondaryContainer: Color = Color(0xFFFFDBC8),
    override val md_theme_light_onSecondaryContainer: Color = Color(0xFF2B1609),
    override val md_theme_light_tertiary: Color = Color(0xFF626033),
    override val md_theme_light_onTertiary: Color = Color(0xFFFFFFFF),
    override val md_theme_light_tertiaryContainer: Color = Color(0xFFE8E5AC),
    override val md_theme_light_onTertiaryContainer: Color = Color(0xFF1D1D00),
    override val md_theme_light_error: Color = Color(0xFFBA1A1A),
    override val md_theme_light_errorContainer: Color = Color(0xFFFFDAD6),
    override val md_theme_light_onError: Color = Color(0xFFFFFFFF),
    override val md_theme_light_onErrorContainer: Color = Color(0xFF410002),
    override val md_theme_light_background: Color = Color(0xFFFFFBFF),
    override val md_theme_light_onBackground: Color = Color(0xFF201A17),
    override val md_theme_light_surface: Color = Color(0xFFFFFBFF),
    override val md_theme_light_onSurface: Color = Color(0xFF201A17),
    override val md_theme_light_surfaceVariant: Color = Color(0xFFF4DED3),
    override val md_theme_light_onSurfaceVariant: Color = Color(0xFF52443C),
    override val md_theme_light_outline: Color = Color(0xFF85746B),
    override val md_theme_light_inverseOnSurface: Color = Color(0xFFFBEEE9),
    override val md_theme_light_inverseSurface: Color = Color(0xFF362F2C),
    override val md_theme_light_inversePrimary: Color = Color(0xFFFFB68B),
    override val md_theme_light_shadow: Color = Color(0xFF000000),
    override val md_theme_light_surfaceTint: Color = Color(0xFF97480B),
    override val md_theme_light_outlineVariant: Color = Color(0xFFD7C2B8),
    override val md_theme_light_scrim: Color = Color(0xFF000000),

    override val md_theme_dark_primary: Color = Color(0xFFFFB68B),
    override val md_theme_dark_onPrimary: Color = Color(0xFF522300),
    override val md_theme_dark_primaryContainer: Color = Color(0xFF753400),
    override val md_theme_dark_onPrimaryContainer: Color = Color(0xFFFFDBC8),
    override val md_theme_dark_secondary: Color = Color(0xFFE5BFAA),
    override val md_theme_dark_onSecondary: Color = Color(0xFF432B1C),
    override val md_theme_dark_secondaryContainer: Color = Color(0xFF5C4131),
    override val md_theme_dark_onSecondaryContainer: Color = Color(0xFFFFDBC8),
    override val md_theme_dark_tertiary: Color = Color(0xFFCCC992),
    override val md_theme_dark_onTertiary: Color = Color(0xFF333209),
    override val md_theme_dark_tertiaryContainer: Color = Color(0xFF4A491E),
    override val md_theme_dark_onTertiaryContainer: Color = Color(0xFFE8E5AC),
    override val md_theme_dark_error: Color = Color(0xFFFFB4AB),
    override val md_theme_dark_errorContainer: Color = Color(0xFF93000A),
    override val md_theme_dark_onError: Color = Color(0xFF690005),
    override val md_theme_dark_onErrorContainer: Color = Color(0xFFFFDAD6),
    override val md_theme_dark_background: Color = Color(0xFF201A17),
    override val md_theme_dark_onBackground: Color = Color(0xFFECE0DB),
    override val md_theme_dark_surface: Color = Color(0xFF201A17),
    override val md_theme_dark_onSurface: Color = Color(0xFFECE0DB),
    override val md_theme_dark_surfaceVariant: Color = Color(0xFF52443C),
    override val md_theme_dark_onSurfaceVariant: Color = Color(0xFFD7C2B8),
    override val md_theme_dark_outline: Color = Color(0xFF9F8D84),
    override val md_theme_dark_inverseOnSurface: Color = Color(0xFF201A17),
    override val md_theme_dark_inverseSurface: Color = Color(0xFFECE0DB),
    override val md_theme_dark_inversePrimary: Color = Color(0xFF97480B),
    override val md_theme_dark_shadow: Color = Color(0xFF000000),
    override val md_theme_dark_surfaceTint: Color = Color(0xFFFFB68B),
    override val md_theme_dark_outlineVariant: Color = Color(0xFF52443C),
    override val md_theme_dark_scrim: Color = Color(0xFF000000),


    override val seed: Color = Color(0xFFFF9A59)
) : AppColorScheme