package ru.tanec.siderakt.presentation.ui.theme.Colors

import androidx.compose.ui.graphics.Color

data class DefaultColorScheme(
    override val md_theme_light_primary: Color = Color(0xFF5451B7),
    override val md_theme_light_onPrimary: Color = Color(0xFFFFFFFF),
    override val md_theme_light_primaryContainer: Color = Color(0xFFE2DFFF),
    override val md_theme_light_onPrimaryContainer: Color = Color(0xFF0E006A),
    override val md_theme_light_secondary: Color = Color(0xFF5D5C71),
    override val md_theme_light_onSecondary: Color = Color(0xFFFFFFFF),
    override val md_theme_light_secondaryContainer: Color = Color(0xFFE3E0F9),
    override val md_theme_light_onSecondaryContainer: Color = Color(0xFF1A1A2C),
    override val md_theme_light_tertiary: Color = Color(0xFF884589),
    override val md_theme_light_onTertiary: Color = Color(0xFFFFFFFF),
    override val md_theme_light_tertiaryContainer: Color = Color(0xFFFFD6F9),
    override val md_theme_light_onTertiaryContainer: Color = Color(0xFF37003C),
    override val md_theme_light_error: Color = Color(0xFFBA1A1A),
    override val md_theme_light_errorContainer: Color = Color(0xFFFFDAD6),
    override val md_theme_light_onError: Color = Color(0xFFFFFFFF),
    override val md_theme_light_onErrorContainer: Color = Color(0xFF410002),
    override val md_theme_light_background: Color = Color(0xFFFFFBFF),
    override val md_theme_light_onBackground: Color = Color(0xFF1C1B1F),
    override val md_theme_light_surface: Color = Color(0xFFFFFBFF),
    override val md_theme_light_onSurface: Color = Color(0xFF1C1B1F),
    override val md_theme_light_surfaceVariant: Color = Color(0xFFE4E1EC),
    override val md_theme_light_onSurfaceVariant: Color = Color(0xFF47464F),
    override val md_theme_light_outline: Color = Color(0xFF787680),
    override val md_theme_light_inverseOnSurface: Color = Color(0xFFF3EFF4),
    override val md_theme_light_inverseSurface: Color = Color(0xFF313034),
    override val md_theme_light_inversePrimary: Color = Color(0xFFC3C0FF),
    override val md_theme_light_shadow: Color = Color(0xFF000000),
    override val md_theme_light_surfaceTint: Color = Color(0xFF5451B7),
    override val md_theme_light_outlineVariant: Color = Color(0xFFC8C5D0),
    override val md_theme_light_scrim: Color = Color(0xFF000000),
    override val md_theme_dark_primary: Color = Color(0xFFC3C0FF),
    override val md_theme_dark_onPrimary: Color = Color(0xFF241D87),
    override val md_theme_dark_primaryContainer: Color = Color(0xFF3C389D),
    override val md_theme_dark_onPrimaryContainer: Color = Color(0xFFE2DFFF),
    override val md_theme_dark_secondary: Color = Color(0xFFC7C4DD),
    override val md_theme_dark_onSecondary: Color = Color(0xFF2F2F42),
    override val md_theme_dark_secondaryContainer: Color = Color(0xFF464559),
    override val md_theme_dark_onSecondaryContainer: Color = Color(0xFFE3E0F9),
    override val md_theme_dark_tertiary: Color = Color(0xFFFBACF8),
    override val md_theme_dark_onTertiary: Color = Color(0xFF531457),
    override val md_theme_dark_tertiaryContainer: Color = Color(0xFF6D2D6F),
    override val md_theme_dark_onTertiaryContainer: Color = Color(0xFFFFD6F9),
    override val md_theme_dark_error: Color = Color(0xFFFFB4AB),
    override val md_theme_dark_errorContainer: Color = Color(0xFF93000A),
    override val md_theme_dark_onError: Color = Color(0xFF690005),
    override val md_theme_dark_onErrorContainer: Color = Color(0xFFFFDAD6),
    override val md_theme_dark_background: Color = Color(0xFF1C1B1F),
    override val md_theme_dark_onBackground: Color = Color(0xFFE5E1E6),
    override val md_theme_dark_surface: Color = Color(0xFF1C1B1F),
    override val md_theme_dark_onSurface: Color = Color(0xFFE5E1E6),
    override val md_theme_dark_surfaceVariant: Color = Color(0xFF47464F),
    override val md_theme_dark_onSurfaceVariant: Color = Color(0xFFC8C5D0),
    override val md_theme_dark_outline: Color = Color(0xFF928F9A),
    override val md_theme_dark_inverseOnSurface: Color = Color(0xFF1C1B1F),
    override val md_theme_dark_inverseSurface: Color = Color(0xFFE5E1E6),
    override val md_theme_dark_inversePrimary: Color = Color(0xFF5451B7),
    override val md_theme_dark_shadow: Color = Color(0xFF000000),
    override val md_theme_dark_surfaceTint: Color = Color(0xFFC3C0FF),
    override val md_theme_dark_outlineVariant: Color = Color(0xFF47464F),
    override val md_theme_dark_scrim: Color = Color(0xFF000000),
    override val seed: Color = Color(0xFF9795FF)

) : AppColorScheme
