package ru.tanec.siderakt.presentation.ui.theme.Colors

import androidx.compose.ui.graphics.Color

data class DefaultColorScheme(
    override val md_theme_light_primary: Color = Color(0xFF6C42C8),
    override val md_theme_light_onPrimary: Color = Color(0xFFFFFFFF),
    override val md_theme_light_primaryContainer: Color = Color(0xFFE9DDFF),
    override val md_theme_light_onPrimaryContainer: Color = Color(0xFF23005C),
    override val md_theme_light_secondary: Color = Color(0xFF625B70),
    override val md_theme_light_onSecondary: Color = Color(0xFFFFFFFF),
    override val md_theme_light_secondaryContainer: Color = Color(0xFFE8DEF8),
    override val md_theme_light_onSecondaryContainer: Color = Color(0xFF1E192B),
    override val md_theme_light_tertiary: Color = Color(0xFF7E525F),
    override val md_theme_light_onTertiary: Color = Color(0xFFFFFFFF),
    override val md_theme_light_tertiaryContainer: Color = Color(0xFFFFD9E2),
    override val md_theme_light_onTertiaryContainer: Color = Color(0xFF31101C),
    override val md_theme_light_error: Color = Color(0xFFBA1A1A),
    override val md_theme_light_errorContainer: Color = Color(0xFFFFDAD6),
    override val md_theme_light_onError: Color = Color(0xFFFFFFFF),
    override val md_theme_light_onErrorContainer: Color = Color(0xFF410002),
    override val md_theme_light_background: Color = Color(0xFFFFFBFF),
    override val md_theme_light_onBackground: Color = Color(0xFF1C1B1E),
    override val md_theme_light_surface: Color = Color(0xFFFFFBFF),
    override val md_theme_light_onSurface: Color = Color(0xFF1C1B1E),
    override val md_theme_light_surfaceVariant: Color = Color(0xFFE7E0EB),
    override val md_theme_light_onSurfaceVariant: Color = Color(0xFF49454E),
    override val md_theme_light_outline: Color = Color(0xFF7A757F),
    override val md_theme_light_inverseOnSurface: Color = Color(0xFFF5EFF4),
    override val md_theme_light_inverseSurface: Color = Color(0xFF323033),
    override val md_theme_light_inversePrimary: Color = Color(0xFFD0BCFF),
    override val md_theme_light_shadow: Color = Color(0xFF000000),
    override val md_theme_light_surfaceTint: Color = Color(0xFF6C42C8),
    override val md_theme_light_outlineVariant: Color = Color(0xFFCAC4CF),
    override val md_theme_light_scrim: Color = Color(0xFF000000),

    override val md_theme_dark_primary: Color = Color(0xFFD0BCFF),
    override val md_theme_dark_onPrimary: Color = Color(0xFF3C0091),
    override val md_theme_dark_primaryContainer: Color = Color(0xFF5424AF),
    override val md_theme_dark_onPrimaryContainer: Color = Color(0xFFE9DDFF),
    override val md_theme_dark_secondary: Color = Color(0xFFCCC2DB),
    override val md_theme_dark_onSecondary: Color = Color(0xFF332D41),
    override val md_theme_dark_secondaryContainer: Color = Color(0xFF4A4458),
    override val md_theme_dark_onSecondaryContainer: Color = Color(0xFFE8DEF8),
    override val md_theme_dark_tertiary: Color = Color(0xFFF0B8C7),
    override val md_theme_dark_onTertiary: Color = Color(0xFF4A2531),
    override val md_theme_dark_tertiaryContainer: Color = Color(0xFF633B48),
    override val md_theme_dark_onTertiaryContainer: Color = Color(0xFFFFD9E2),
    override val md_theme_dark_error: Color = Color(0xFFFFB4AB),
    override val md_theme_dark_errorContainer: Color = Color(0xFF93000A),
    override val md_theme_dark_onError: Color = Color(0xFF690005),
    override val md_theme_dark_onErrorContainer: Color = Color(0xFFFFDAD6),
    override val md_theme_dark_background: Color = Color(0xFF1C1B1E),
    override val md_theme_dark_onBackground: Color = Color(0xFFE6E1E6),
    override val md_theme_dark_surface: Color = Color(0xFF1C1B1E),
    override val md_theme_dark_onSurface: Color = Color(0xFFE6E1E6),
    override val md_theme_dark_surfaceVariant: Color = Color(0xFF49454E),
    override val md_theme_dark_onSurfaceVariant: Color = Color(0xFFCAC4CF),
    override val md_theme_dark_outline: Color = Color(0xFF948F99),
    override val md_theme_dark_inverseOnSurface: Color = Color(0xFF1C1B1E),
    override val md_theme_dark_inverseSurface: Color = Color(0xFFE6E1E6),
    override val md_theme_dark_inversePrimary: Color = Color(0xFF6C42C8),
    override val md_theme_dark_shadow: Color = Color(0xFF000000),
    override val md_theme_dark_surfaceTint: Color = Color(0xFFD0BCFF),
    override val md_theme_dark_outlineVariant: Color = Color(0xFF49454E),
    override val md_theme_dark_scrim: Color = Color(0xFF000000),


    override val seed: Color = Color(0xFFA078FF)
) : AppColorScheme
