package ru.tanec.siderakt.presentation.ui.theme.Colors

import androidx.compose.ui.graphics.Color

data class DefaultColorScheme(
    override val md_theme_light_primary: Color = Color(0xFF006491),
    override val md_theme_light_onPrimary: Color = Color(0xFFFFFFFF),
    override val md_theme_light_primaryContainer: Color = Color(0xFFC9E6FF),
    override val md_theme_light_onPrimaryContainer: Color = Color(0xFF001E2F),
    override val md_theme_light_secondary: Color = Color(0xFF4F606E),
    override val md_theme_light_onSecondary: Color = Color(0xFFFFFFFF),
    override val md_theme_light_secondaryContainer: Color = Color(0xFFD3E5F5),
    override val md_theme_light_onSecondaryContainer: Color = Color(0xFF0C1D29),
    override val md_theme_light_tertiary: Color = Color(0xFF64597B),
    override val md_theme_light_onTertiary: Color = Color(0xFFFFFFFF),
    override val md_theme_light_tertiaryContainer: Color = Color(0xFFEADDFF),
    override val md_theme_light_onTertiaryContainer: Color = Color(0xFF201635),
    override val md_theme_light_error: Color = Color(0xFFBA1A1A),
    override val md_theme_light_errorContainer: Color = Color(0xFFFFDAD6),
    override val md_theme_light_onError: Color = Color(0xFFFFFFFF),
    override val md_theme_light_onErrorContainer: Color = Color(0xFF410002),
    override val md_theme_light_background: Color = Color(0xFFFCFCFF),
    override val md_theme_light_onBackground: Color = Color(0xFF191C1E),
    override val md_theme_light_surface: Color = Color(0xFFFCFCFF),
    override val md_theme_light_onSurface: Color = Color(0xFF191C1E),
    override val md_theme_light_surfaceVariant: Color = Color(0xFFDDE3EA),
    override val md_theme_light_onSurfaceVariant: Color = Color(0xFF41474D),
    override val md_theme_light_outline: Color = Color(0xFF71787E),
    override val md_theme_light_inverseOnSurface: Color = Color(0xFFF0F0F3),
    override val md_theme_light_inverseSurface: Color = Color(0xFF2E3133),
    override val md_theme_light_inversePrimary: Color = Color(0xFF8ACEFF),
    override val md_theme_light_shadow: Color = Color(0xFF000000),
    override val md_theme_light_surfaceTint: Color = Color(0xFF006491),
    override val md_theme_light_outlineVariant: Color = Color(0xFFC1C7CE),
    override val md_theme_light_scrim: Color = Color(0xFF000000),

    override val md_theme_dark_primary: Color = Color(0xFF8ACEFF),
    override val md_theme_dark_onPrimary: Color = Color(0xFF00344E),
    override val md_theme_dark_primaryContainer: Color = Color(0xFF004C6E),
    override val md_theme_dark_onPrimaryContainer: Color = Color(0xFFC9E6FF),
    override val md_theme_dark_secondary: Color = Color(0xFFB7C9D9),
    override val md_theme_dark_onSecondary: Color = Color(0xFF22323F),
    override val md_theme_dark_secondaryContainer: Color = Color(0xFF384956),
    override val md_theme_dark_onSecondaryContainer: Color = Color(0xFFD3E5F5),
    override val md_theme_dark_tertiary: Color = Color(0xFFCEC0E8),
    override val md_theme_dark_onTertiary: Color = Color(0xFF352B4B),
    override val md_theme_dark_tertiaryContainer: Color = Color(0xFF4C4163),
    override val md_theme_dark_onTertiaryContainer: Color = Color(0xFFEADDFF),
    override val md_theme_dark_error: Color = Color(0xFFFFB4AB),
    override val md_theme_dark_errorContainer: Color = Color(0xFF93000A),
    override val md_theme_dark_onError: Color = Color(0xFF690005),
    override val md_theme_dark_onErrorContainer: Color = Color(0xFFFFDAD6),
    override val md_theme_dark_background: Color = Color(0xFF191C1E),
    override val md_theme_dark_onBackground: Color = Color(0xFFE2E2E5),
    override val md_theme_dark_surface: Color = Color(0xFF191C1E),
    override val md_theme_dark_onSurface: Color = Color(0xFFE2E2E5),
    override val md_theme_dark_surfaceVariant: Color = Color(0xFF41474D),
    override val md_theme_dark_onSurfaceVariant: Color = Color(0xFFC1C7CE),
    override val md_theme_dark_outline: Color = Color(0xFF8B9198),
    override val md_theme_dark_inverseOnSurface: Color = Color(0xFF191C1E),
    override val md_theme_dark_inverseSurface: Color = Color(0xFFE2E2E5),
    override val md_theme_dark_inversePrimary: Color = Color(0xFF006491),
    override val md_theme_dark_shadow: Color = Color(0xFF000000),
    override val md_theme_dark_surfaceTint: Color = Color(0xFF8ACEFF),
    override val md_theme_dark_outlineVariant: Color = Color(0xFF41474D),
    override val md_theme_dark_scrim: Color = Color(0xFF000000),


    override val seed: Color = Color(0xFFA4A3A4)

): AppColorScheme
